# Generated by Django 5.2 on 2025-05-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200)),
                ('officer_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
