# Generated by Django 5.2.1 on 2025-05-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_cctv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='location',
        ),
        migrations.AlterModelTable(
            name='cctv',
            table='cctv',
        ),
    ]
